### PR TITLE
Remove ACLOCAL_AMFLAGS recommendation from README

### PR DESCRIPTION
**Pull request by mcatanzaro**
It used to be common to modify ACLOCAL_AMFLAGS in the top-level Makefile.am in order to cause m4 macros to be installed, but this variable is deprecated and should not be used anymore. It will not work in future versions of Automake. If you call aclocal --install in your autogen.sh then you do not need it. In the future, autoreconf --install will handle this automatically.

### CODE REVIEW

**Comment by desrt** [comment]
I don't think that this will work, for two reasons.

The first is that we should make it possible for projects not to have autogen.sh files by using "pure autotools" and generating the needed stuff via autoreconf.

The second is that the problem doesn't have to do with first-time autogen but rather what happens when the tools get re-run in response to changes.  That's what this line in Makefile.am is used for, and it needs to stay there until a widely-available released autoconf version no longer needs it.

**Comment by mcatanzaro** [comment]
I guess I've never noticed any issues, because I usually do clean builds after messing around with the build system.

**Comment by desrt** [comment]
Going to close this one then.

**Comment by mcatanzaro** [comment]
Note:

```
  - The ACLOCAL_AMFLAGS special make variable will be fully deprecated in
    Automake 2.0: it will raise warnings in the "obsolete" category (but
    still no hard error of course, for compatibilities with the many, many
    packages that still relies on that variable).  You are advised to
    start relying on the new Automake support for AC_CONFIG_MACRO_DIRS
    instead (which was introduced in Automake 1.13).
```

**Pull request closed without merging**
